### ISSUE TITLE
Is the View Pattern really necessary here?

### ISSUE THREAD

**Issue by folivetti** [alt-romes/hegg#19]
I'm not very proficient with ViewPatterns, but in this particular line couldn't we just use:

```haskell
auxs <- toList <$> traverse aux p
```

in my opinion it would make it much clearer what this line is doing.

https://github.com/alt-romes/hegg/blob/ef0837b7c7c55b826e496e29aeed454dbf9601a8/src/Data/Equality/Matching.hs#L118

**Comment by alt-romes** [comment]
@folivetti Surely, there's no particular reason for it. Might have sprung up from things moving around and ended up just being `toList` which I agree is not great.

Feel free to open a PR 👍 !

**Comment by folivetti** [comment]
Thanks! Will do that very soon, I'm taking my spare time to read and understand all your code, hopefully I'll start contributing by next month, including the Debug implementation.

**Comment by alt-romes** [comment]
> Thanks! Will do that very soon, I'm taking my spare time to read and understand all your code, hopefully I'll start contributing by next month, including the Debug implementation.

It's very exciting to hear so!

I have cooking the redesign of Analysis in another branch, which will change up some things, but I haven't found time to finish it yet

Thanks!
